import express from 'express';
import cors from 'cors';
import { randomUUID } from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { auditFiles } from './qa.js';
import { buildDesignSystem, buildAssetManifest, writeLocalAssets } from './design.js';
import { buildOrchestration, AGENTS, createRunState } from './orchestrator.js';
import { annotateComponents, extractComponents, componentContract } from './components.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECTS_DIR = path.join(__dirname, 'projects');
const VERSIONS_DIR = path.join(__dirname, 'versions');
await fs.mkdir(PROJECTS_DIR, { recursive: true });
await fs.mkdir(VERSIONS_DIR, { recursive: true });

const OLLAMA_URL = process.env.OLLAMA_URL || 'http://127.0.0.1:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'qwen2.5-coder:7b';
const app = express();
app.use(cors());
app.use(express.json({ limit: '12mb' }));

function plan(prompt) {
  const p = prompt.toLowerCase();
  const type = p.includes('فروش') || p.includes('فروشگاه') || p.includes('ecommerce') ? 'E-commerce' : p.includes('کلینیک') || p.includes('clinic') ? 'Clinic' : p.includes('portfolio') || p.includes('نمونه کار') ? 'Portfolio' : 'Premium Website';
  const pages = type === 'E-commerce' ? ['Home', 'Products', 'Product Detail', 'About', 'Contact'] : ['Home', 'About', 'Services', 'Projects', 'Contact'];
  const designSystem = buildDesignSystem(prompt);
  return { id: randomUUID(), name: `${type} Project`, description: prompt.slice(0, 500), pages, animationLevel: (p.includes('انیمیشن') || p.includes('3d') || p.includes('سه بعدی')) ? 'Cinematic' : 'Premium', threeD: p.includes('3d') || p.includes('سه بعدی'), features: ['Responsive', 'SEO', 'AEO', 'GEO', 'Accessibility', 'Performance', 'Design System', 'Asset Agent', 'GSAP Motion', '3D Ready'], designSystem };
}
function escapeHtml(value = '') { return value.replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c])); }
function makeSite(spec, prompt) {
  const title = escapeHtml(spec.name.replace(' Project', '')); const description = escapeHtml(prompt.slice(0, 150));
  const three = spec.threeD ? `<div class="scene" aria-label="Interactive visual"><div class="orb3d"></div><div class="ring"></div><div class="grid"></div></div>` : '';
  const html = annotateComponents(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | سایت حرفه‌ای</title><meta name="description" content="${description}"><link rel="canonical" href="https://example.com/"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebSite',name:title,description:prompt.slice(0,150)})}</script><link rel="stylesheet" href="style.css"></head><body><header><a class="logo" href="#">${title}</a><nav>${spec.pages.map(p=>`<a href="#${p.toLowerCase().replace(/ /g,'-')}">${p}</a>`).join('')}</nav><button class="cta">شروع پروژه</button></header><main><section class="hero"><div class="copy"><span class="eyebrow">AI GENERATED • SEO / AEO / GEO READY</span><h1>یک تجربه دیجیتال <em>متفاوت</em></h1><p>${description}</p><div class="actions"><button class="primary">مشاهده پروژه</button><button class="ghost">کشف بیشتر ↓</button></div></div>${three}</section><section class="features" id="services"><article><b>01</b><h2>طراحی حرفه‌ای</h2><p>سیستم طراحی واکنش‌گرا با ساختار قابل توسعه.</p></article><article><b>02</b><h2>Performance</h2><p>ساختار سبک و آماده بهینه‌سازی Core Web Vitals.</p></article><article><b>03</b><h2>AI Search</h2><p>ساختار محتوایی آماده SEO، AEO و GEO.</p></article></section><section class="answer" id="about"><span>ANSWER READY</span><h2>این سایت چه کاری انجام می‌دهد؟</h2><p>محتوا با ساختار معنایی، پاسخ‌های مستقیم و داده‌های ساختاریافته طراحی شده تا برای کاربران و موتورهای جستجو قابل فهم باشد.</p></section></main><footer>Generated by AI Web Studio</footer><script src="app.js"></script></body></html>`);
  const css = `:root{font-family:Arial,sans-serif;color:#eef2ff;background:#070912}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 10%,#273b70 0,#090c16 34%,#05060a 100%);min-height:100vh}header{height:76px;padding:0 6%;display:flex;align-items:center;gap:28px;border-bottom:1px solid #ffffff12;backdrop-filter:blur(16px);position:sticky;top:0;z-index:5}.logo{color:white;text-decoration:none;font-weight:800;margin-left:auto}nav{display:flex;gap:18px}nav a{color:#9da7ba;text-decoration:none;font-size:13px}.cta,.primary{border:0;border-radius:12px;padding:11px 17px;font-weight:800;cursor:pointer}.cta{background:#edf2ff;color:#070912}.hero{min-height:620px;padding:8% 8%;display:flex;align-items:center;gap:8%;overflow:hidden}.copy{max-width:650px}.eyebrow,.answer span{font-size:10px;letter-spacing:2px;color:#8ca4ff}.hero h1{font-size:clamp(48px,7vw,92px);line-height:.98;margin:22px 0}.hero h1 em{font-style:normal;background:linear-gradient(90deg,#fff,#8197ff);color:transparent;background-clip:text}.hero p,.answer p{color:#9ca6bb;line-height:2;font-size:16px}.actions{display:flex;gap:10px;margin-top:28px}.primary{background:#fff;color:#080a10}.ghost{background:#ffffff08;border:1px solid #ffffff14;color:#dfe5f2;border-radius:12px;padding:11px 17px}.scene{width:420px;height:420px;position:relative;flex:none}.orb3d{position:absolute;inset:70px;border-radius:50%;background:radial-gradient(circle at 30% 25%,#fff,#93a7ff 8%,#30418d 35%,#080b19 70%);box-shadow:0 0 90px #6078ff77;animation:float 5s ease-in-out infinite}.ring{position:absolute;inset:45px;border:1px solid #93a7ff77;border-radius:50%;transform:rotate(65deg) scaleY(.35);animation:spin 9s linear infinite}.grid{position:absolute;inset:0;background:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:32px 32px;mask-image:radial-gradient(circle,#000 20%,transparent 70%);opacity:.45}.features{padding:5% 8%;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.features article,.answer{border:1px solid #ffffff12;background:#ffffff06;border-radius:20px;padding:28px}.features b{color:#8197ff}.features h2{font-size:22px}.features p{color:#8f99ae;line-height:1.9}.answer{margin:3% 8% 8%;max-width:850px}.answer h2{font-size:34px}footer{padding:30px 8%;color:#69748b;border-top:1px solid #ffffff0d}@keyframes float{50%{transform:translateY(-15px) rotate(4deg)}}@keyframes spin{to{transform:rotate(425deg) scaleY(.35)}}@media(max-width:800px){nav{display:none}.hero{padding-top:70px;display:block}.scene{width:300px;height:300px;margin:50px auto}.features{grid-template-columns:1fr}.hero h1{font-size:52px}}`;
  return {'index.html':html,'style.css':css,'app.js':`document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const el=document.querySelector(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}}));`,'robots.txt':'User-agent: *\nAllow: /\nSitemap: https://example.com/sitemap.xml\n','sitemap.xml':'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/</loc></url></urlset>'};
}
function cleanJsonText(text) { const raw=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim(); const start=raw.indexOf('{'), end=raw.lastIndexOf('}'); if(start<0||end<=start) throw new Error('AI returned invalid JSON'); return raw.slice(start,end+1); }
function validateFiles(files) { if(!files||typeof files!=='object'||Array.isArray(files)) throw new Error('AI files payload is invalid'); const allowed=/^(index|style|app|robots|sitemap)\.[a-z0-9]+$/i; const result={}; for(const [name,content] of Object.entries(files)){const safe=path.basename(name); if(safe!==name||name.includes('..')||!allowed.test(name)) continue; if(typeof content!=='string') continue; result[safe]=content.slice(0,900000);} if(!result['index.html']) throw new Error('AI did not return index.html'); return result; }
async function ollamaGenerate(prompt,spec,currentFiles=null,instruction=null){
  const editing = currentFiles && Object.keys(currentFiles).length;
  const system=`You are the File Agent inside AI Web Studio. ${editing?'You are modifying an existing website, not starting from scratch. Preserve working functionality and change only what the user requests.':'Create a polished production-style website.'} Use HTML, CSS and vanilla JavaScript. Return ONLY valid JSON: {"files":{"index.html":"...","style.css":"...","app.js":"...","robots.txt":"...","sitemap.xml":"..."}}. No markdown. Keep paths flat. Make semantic, responsive, accessible, SEO/AEO/GEO-ready code. Never expose secrets.`;
  const user=editing?`Project specification:\n${JSON.stringify(spec,null,2)}\n\nUser change request:\n${instruction}\n\nCurrent files:\n${JSON.stringify(currentFiles)}`:`Project specification:\n${JSON.stringify(spec,null,2)}\n\nUser request:\n${prompt}`;
  const response=await fetch(`${OLLAMA_URL.replace(/\/$/,'')}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:OLLAMA_MODEL,system,prompt:user,stream:false,format:'json',options:{temperature:0.3}})});
  if(!response.ok) throw new Error(`Ollama HTTP ${response.status}`); const data=await response.json(); const parsed=JSON.parse(cleanJsonText(data.response)); return validateFiles(parsed.files);
}
async function snapshotProject(id, files, label='manual') {
  const safeId=path.basename(id); if(safeId!==id||id.includes('..')) throw new Error('Invalid project id');
  const dir=path.join(VERSIONS_DIR,safeId); await fs.mkdir(dir,{recursive:true});
  const versionId=`${Date.now()}-${randomUUID().slice(0,8)}`; const vdir=path.join(dir,versionId); await fs.mkdir(vdir,{recursive:true});
  await fs.writeFile(path.join(vdir,'meta.json'),JSON.stringify({versionId,label,createdAt:new Date().toISOString(),files:Object.keys(files)},null,2));
  await Promise.all(Object.entries(files).map(([name,content])=>fs.writeFile(path.join(vdir,path.basename(name)),content,'utf8')));
  return {versionId,label,createdAt:new Date().toISOString(),files:Object.keys(files)};
}
async function listVersions(id){
  const safeId=path.basename(id); if(safeId!==id) throw new Error('Invalid project id'); const dir=path.join(VERSIONS_DIR,id);
  try{const names=await fs.readdir(dir); const out=[]; for(const name of names){try{const m=JSON.parse(await fs.readFile(path.join(dir,name,'meta.json'),'utf8'));out.push(m)}catch{}} return out.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}catch{return []}
}
async function restoreVersion(id,versionId){
  const safeId=path.basename(id), safeVersion=path.basename(versionId); if(safeId!==id||safeVersion!==versionId) throw new Error('Invalid version');
  const dir=path.join(VERSIONS_DIR,id,versionId); const names=['index.html','style.css','app.js','robots.txt','sitemap.xml']; const files={};
  for(const name of names){try{files[name]=await fs.readFile(path.join(dir,name),'utf8')}catch{}} if(!files['index.html']) throw new Error('Version not found'); return files;
}

function diffLines(before='', after='') {
  const a=String(before).split('\n'), b=String(after).split('\n');
  const n=a.length,m=b.length;
  const dp=Array.from({length:n+1},()=>Array(m+1).fill(0));
  for(let i=n-1;i>=0;i--) for(let j=m-1;j>=0;j--) dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);
  const out=[]; let i=0,j=0;
  while(i<n&&j<m){
    if(a[i]===b[j]){out.push({type:'context',line:a[i],oldLine:i+1,newLine:j+1});i++;j++;}
    else if(dp[i+1][j]>=dp[i][j+1]){out.push({type:'remove',line:a[i],oldLine:i+1});i++;}
    else{out.push({type:'add',line:b[j],newLine:j+1});j++;}
  }
  while(i<n) out.push({type:'remove',line:a[i++],oldLine:i});
  while(j<m) out.push({type:'add',line:b[j++],newLine:j});
  return out;
}
async function aiCodeAction(action, code, language='html', context='') {
  const prompt=`You are an expert web engineer. Action: ${action}. Language: ${language}. Return ONLY JSON {"result":"..."}. Keep the answer concise but technically useful. Code/context:\n${code}\n\nExtra context:\n${context}`;
  const response=await fetch(`${OLLAMA_URL.replace(/\/$/,'')}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:OLLAMA_MODEL,prompt,stream:false,format:'json',options:{temperature:0.2}})});
  if(!response.ok) throw new Error(`Ollama HTTP ${response.status}`);
  const data=await response.json(); const parsed=JSON.parse(cleanJsonText(data.response));
  if(typeof parsed.result!=='string') throw new Error('AI returned invalid result'); return parsed.result;
}

function terminalCommand(command, id){
  const c=String(command||'').trim();
  const allowed=['help','status','files','qa','agents','version','clear'];
  if(!allowed.includes(c)) return {ok:false,output:`Command blocked. Allowed: ${allowed.join(', ')}`};
  if(c==='help') return {ok:true,output:'help  status  files  qa  agents  version  clear'};
  if(c==='version') return {ok:true,output:'AI Web Studio V2.0.1 — Local-first Production Studio'};
  if(c==='status') return {ok:true,output:`Project: ${id}\nRuntime: local\nSecurity: sandboxed command set`};
  if(c==='files') return {ok:true,output:'Use the File Explorer to inspect and edit project files.'};
  if(c==='qa') return {ok:true,output:'Run QA from the Studio toolbar for the current project.'};
  if(c==='agents') return {ok:true,output:'Architect → Design → Asset → UI → Code → SEO → AEO → GEO → 3D → QA'};
  return {ok:true,output:''};
}
async function saveFiles(id,files){const safeId=path.basename(id); if(safeId!==id||id.includes('..')) throw new Error('Invalid project id'); const dir=path.join(PROJECTS_DIR,id); await fs.mkdir(dir,{recursive:true}); await Promise.all(Object.entries(files).map(([name,content])=>fs.writeFile(path.join(dir,name),content,'utf8'))); await snapshotProject(id,files,'save'); return dir;}
async function readProject(id){const safeId=path.basename(id); if(safeId!==id) throw new Error('Invalid project id'); const dir=path.join(PROJECTS_DIR,id); const names=['index.html','style.css','app.js','robots.txt','sitemap.xml']; const files={}; for(const name of names){try{files[name]=await fs.readFile(path.join(dir,name),'utf8')}catch{}} return files;}

app.get('/api/health',(req,res)=>res.json({ok:true,version:'2.0.1',ai:'multi-agent+ollama+file-agent+qa+design+assets+library'}));
app.get('/api/agents',(req,res)=>res.json({agents:AGENTS}));
app.post('/api/orchestrate',async(req,res)=>{try{const prompt=String(req.body?.prompt||'').trim();if(!prompt)return res.status(400).json({error:'prompt required'});const spec=req.body?.spec||plan(prompt);const orchestration=buildOrchestration(prompt,spec,req.body?.files||null);res.json({ok:true,orchestration});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/orchestrate/run',async(req,res)=>{
  const prompt=String(req.body?.prompt||'').trim();
  if(!prompt)return res.status(400).json({error:'prompt required'});
  const spec=req.body?.spec||plan(prompt); const state=createRunState(prompt,spec); const logs=[];
  let files=null; let provider='template-fallback';
  const step=(id)=>state.steps.find(x=>x.id===id);
  const start=(id,msg)=>{state.current=id; const x=step(id); if(x){x.status='running';x.startedAt=new Date().toISOString();x.message=msg||'';} logs.push({type:'start',agent:id,message:msg||''});};
  const done=(id,msg)=>{const x=step(id);if(x){x.status='done';x.finishedAt=new Date().toISOString();x.message=msg||'';}logs.push({type:'done',agent:id,message:msg||''});};
  const fail=(id,e)=>{const x=step(id);if(x){x.status='failed';x.finishedAt=new Date().toISOString();x.message=e.message;}state.errors.push({agent:id,error:e.message});logs.push({type:'error',agent:id,message:e.message});};
  try{
    start('architect','تحلیل نیازمندی، صفحات و قابلیت‌ها'); await new Promise(r=>setTimeout(r,30)); done('architect',`${spec.pages.length} pages planned`);
    start('design','ساخت Design System و Motion tokens'); const design=spec.designSystem||buildDesignSystem(prompt); spec.designSystem=design; done('design',design.name||'Adaptive design system');
    start('asset','ساخت manifest و assets محلی'); const id=spec.id||randomUUID(); spec.id=id; const dir=path.join(PROJECTS_DIR,id); await fs.mkdir(dir,{recursive:true}); const manifest=buildAssetManifest(spec,design); await writeLocalAssets(dir,design); await fs.writeFile(path.join(dir,'asset-manifest.json'),JSON.stringify(manifest,null,2)); done('asset',`${manifest.assets?.length||0} assets prepared`);
    start('ui','تعیین ساختار semantic و responsive'); await new Promise(r=>setTimeout(r,20)); done('ui','Responsive UI contract created');
    start('code','تولید کد پروژه'); if(req.body?.useOllama!==false){try{files=await ollamaGenerate(prompt,spec);provider='ollama';}catch(e){state.errors.push({agent:'code',error:e.message});logs.push({type:'fallback',agent:'code',message:e.message});}} if(!files)files=makeSite(spec,prompt); await saveFiles(id,files); done('code',provider==='ollama'?'Generated with Ollama':'Generated with deterministic fallback');
    for(const a of ['seo','aeo','geo']){start(a,a==='seo'?'بهینه‌سازی SEO':a==='aeo'?'ساختار Answer-ready و AEO':'Entity clarity و GEO'); await new Promise(r=>setTimeout(r,20)); done(a,'Requirements passed to final code/QA context');}
    if(state.pipeline.includes('3d')){start('3d','بررسی و آماده‌سازی مسیر Three.js / motion'); await new Promise(r=>setTimeout(r,20)); done('3d','3D-ready pipeline enabled');}
    start('qa','اجرای QA نهایی'); let audit=auditFiles(files); done('qa',`${audit.score}/100 • ${audit.summary.passed}/${audit.summary.total} checks passed`);
    if(req.body?.autoHeal && audit.checks.some(c=>!c.pass)){
      logs.push({type:'heal-start',message:'QA failures detected; starting autonomous repair'});
      const maxRounds=Math.min(Math.max(Number(req.body?.maxRounds)||2,1),3);
      for(let round=1;round<=maxRounds;round++){
        const failures=audit.checks.filter(c=>!c.pass); if(!failures.length)break;
        logs.push({type:'heal-round',round,score:audit.score,failures:failures.length});
        try{files=await ollamaGenerate('',spec,files,`Autonomous repair round ${round}. Fix these QA failures with minimal safe changes. Return the complete file set. Failures: ${JSON.stringify(failures)}`); await saveFiles(id,files); audit=auditFiles(files);}catch(e){state.errors.push({agent:'self-healing',error:e.message});logs.push({type:'heal-error',message:e.message});break;}
      }
      logs.push({type:'heal-done',score:audit.score});
    }
    state.status=state.errors.length?'completed-with-warnings':'completed'; state.current=null; state.finishedAt=new Date().toISOString();
    res.json({ok:true,state,logs,id,provider,spec,files:Object.entries(files).map(([name,content])=>({name,content})),qa:audit,orchestration:buildOrchestration(prompt,spec,files)});
  }catch(e){state.status='failed';state.finishedAt=new Date().toISOString();state.errors.push({agent:state.current,error:e.message});res.status(500).json({error:e.message,state,logs});}
});
app.post('/api/design-system', async (req,res)=>{ try { const design=buildDesignSystem(req.body?.prompt||''); res.json({ok:true,design}); } catch(e){ res.status(500).json({error:e.message}); }});
app.post('/api/assets/prepare', async (req,res)=>{ try { const id=req.body?.id; if(!id) throw new Error('Project id required'); const safeId=path.basename(id); if(safeId!==id) throw new Error('Invalid project id'); const dir=path.join(PROJECTS_DIR,id); await fs.mkdir(dir,{recursive:true}); const design=req.body?.design||buildDesignSystem(req.body?.prompt||''); const manifest=buildAssetManifest(req.body?.spec||{},design); await writeLocalAssets(dir,design); await fs.writeFile(path.join(dir,'asset-manifest.json'),JSON.stringify(manifest,null,2)); res.json({ok:true,manifest}); } catch(e){ res.status(500).json({error:e.message}); }});
app.get('/api/components/contract',(req,res)=>res.json({components:componentContract()}));
app.get('/api/project/:id/components',async(req,res)=>{try{const files=await readProject(req.params.id); if(!files['index.html']) return res.status(404).json({error:'project not found'}); res.json({components:extractComponents(files['index.html'])});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/project/:id/components/annotate',async(req,res)=>{try{const files=await readProject(req.params.id); if(!files['index.html']) return res.status(404).json({error:'project not found'}); files['index.html']=annotateComponents(files['index.html']); await saveFiles(req.params.id,files); res.json({ok:true,components:extractComponents(files['index.html']),files:Object.entries(files).map(([name,content])=>({name,content}))});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/project/:id/components/update',async(req,res)=>{try{const files=await readProject(req.params.id); if(!files['index.html']) return res.status(404).json({error:'project not found'}); const type=String(req.body?.type||'').trim(); const changes=req.body?.changes||{}; if(!type||!/^[a-z0-9-]+$/.test(type)) return res.status(400).json({error:'invalid component type'}); let html=files['index.html']; const openRe=new RegExp(`<([a-z0-9-]+)([^>]*data-component=[\"']${type}[\"'][^>]*)>([\s\S]*?)</\\1>`, 'i'); const match=html.match(openRe); if(!match) return res.status(404).json({error:'component not found'}); let body=match[3]; if(typeof changes.title==='string') body=body.replace(/<h[1-6][^>]*>[\s\S]*?<\/h[1-6]>/i,m=>m.replace(/>[\s\S]*?</,'>'+changes.title+'<')); if(typeof changes.description==='string') body=body.replace(/<p([^>]*)>[\s\S]*?<\/p>/i,'<p$1>'+changes.description+'</p>'); const replacement=`<${match[1]}${match[2]}>${body}</${match[1]}>`; html=html.slice(0,match.index)+replacement+html.slice(match.index+match[0].length); files['index.html']=html; await saveFiles(req.params.id,files); res.json({ok:true,components:extractComponents(html),files:Object.entries(files).map(([name,content])=>({name,content}))}); }catch(e){res.status(400).json({error:e.message});}});
app.get('/api/project/:id/qa',async(req,res)=>{try{const files=await readProject(req.params.id);if(!files['index.html'])return res.status(404).json({error:'project not found'});res.json(auditFiles(files));}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/project/:id/self-heal',async(req,res)=>{
  try{
    const id=req.params.id; const current=await readProject(id); if(!current['index.html']) return res.status(404).json({error:'project not found'});
    const maxRounds=Math.min(Math.max(Number(req.body?.maxRounds)||2,1),5); const history=[]; let files=current; let provider='no-change';
    for(let round=1;round<=maxRounds;round++){
      const audit=auditFiles(files); const failures=audit.checks.filter(c=>!c.pass);
      history.push({round,score:audit.score,failures:failures.map(f=>({id:f.id,label:f.label,category:f.category,detail:f.detail}))});
      if(!failures.length){ provider=provider==='no-change'?'already-healthy':provider; break; }
      const instruction=`Self-healing round ${round}. Fix the following QA failures in the existing website. Preserve all working features and design. Do not remove SEO/AEO/GEO, accessibility, responsive behavior, animations, or 3D unless necessary. Make the smallest reliable changes. QA failures:
${JSON.stringify(failures,null,2)}
After fixing, return the complete required file set.`;
      try{ files=await ollamaGenerate('',req.body?.spec||{},files,instruction); provider='ollama-self-healing'; await saveFiles(id,files); }
      catch(e){ history[history.length-1].aiError=e.message; break; }
    }
    const finalAudit=auditFiles(files); await saveFiles(id,files); res.json({id,provider,rounds:history,final:finalAudit,files:Object.entries(files).map(([name,content])=>({name,content}))});
  }catch(e){res.status(500).json({error:e.message});}
});
app.get('/api/ai/status',async(req,res)=>{try{const r=await fetch(`${OLLAMA_URL.replace(/\/$/,'')}/api/tags`);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();res.json({connected:true,url:OLLAMA_URL,model:OLLAMA_MODEL,models:Array.isArray(d.models)?d.models.map(m=>m.name).filter(Boolean):[]});}catch(e){res.json({connected:false,url:OLLAMA_URL,model:OLLAMA_MODEL,models:[],error:e.message});}});
app.post('/api/plan',(req,res)=>{if(!req.body?.prompt)return res.status(400).json({error:'prompt required'});res.json(plan(req.body.prompt));});
app.post('/api/generate',async(req,res)=>{try{const prompt=String(req.body?.prompt||'').trim();if(!prompt)return res.status(400).json({error:'prompt required'});const spec=req.body?.spec||plan(prompt);const id=spec.id||randomUUID();let files,provider='template-fallback',aiError=null;if(req.body?.useOllama!==false){try{files=await ollamaGenerate(prompt,spec);provider='ollama';}catch(e){aiError=e.message;}}if(!files)files=makeSite(spec,prompt);await saveFiles(id,files);
    const design = spec.designSystem || buildDesignSystem(prompt);
    const manifest = buildAssetManifest(spec, design);
    await writeLocalAssets(path.join(PROJECTS_DIR,id), design);
    await fs.writeFile(path.join(PROJECTS_DIR,id,'asset-manifest.json'), JSON.stringify(manifest,null,2));res.json({id,name:spec.name,spec,provider,aiError,files:Object.entries(files).map(([name,content])=>({name,content}))});}catch(e){res.status(500).json({error:e.message});}});
// V2.0 Ultimate Studio APIs
const LIBRARY_DIR = path.join(__dirname, 'library');
const RUNS_DIR = path.join(__dirname, 'runs');
await fs.mkdir(LIBRARY_DIR, { recursive: true });
await fs.mkdir(RUNS_DIR, { recursive: true });

function safeSlug(v='item') { return String(v).toLowerCase().replace(/[^a-z0-9-_]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80) || 'item'; }
function safeLibraryId(v='') { const id=path.basename(String(v)); if(!id || id!==String(v) || id.includes('..')) throw new Error('Invalid library id'); return id; }

app.get('/api/project/:id/files', async (req,res)=>{
  try { const files=await readProject(req.params.id); res.json({id:req.params.id,files:Object.entries(files).map(([name,content])=>({name,content}))}); }
  catch(e){ res.status(404).json({error:e.message}); }
});

app.get('/api/library', async (req,res)=>{
  try {
    const entries=await fs.readdir(LIBRARY_DIR,{withFileTypes:true}); const items=[];
    for(const e of entries){ if(!e.isDirectory()) continue; try{ items.push(JSON.parse(await fs.readFile(path.join(LIBRARY_DIR,e.name,'manifest.json'),'utf8'))); }catch{} }
    items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))); res.json({items});
  } catch(e){res.status(500).json({error:e.message});}
});

app.post('/api/library/save', async (req,res)=>{
  try {
    const item=req.body?.item||{}; const id=safeSlug(item.id||item.name||randomUUID()); const dir=path.join(LIBRARY_DIR,id); await fs.mkdir(dir,{recursive:true});
    const manifest={id,name:item.name||id,type:item.type||'component',description:item.description||'',tags:Array.isArray(item.tags)?item.tags:[],component:item.component||null,design:item.design||null,createdAt:item.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};
    await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)); if(typeof item.content==='string') await fs.writeFile(path.join(dir,'content.txt'),item.content); res.json({ok:true,item:manifest});
  }catch(e){res.status(400).json({error:e.message});}
});

app.get('/api/library/:id', async (req,res)=>{try{const id=safeLibraryId(req.params.id); const dir=path.join(LIBRARY_DIR,id); const item=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8')); let content=null; try{content=await fs.readFile(path.join(dir,'content.txt'),'utf8')}catch{} res.json({item,content});}catch(e){res.status(404).json({error:e.message});}});

app.delete('/api/library/:id', async (req,res)=>{try{const id=safeLibraryId(req.params.id); await fs.rm(path.join(LIBRARY_DIR,id),{recursive:true,force:true}); res.json({ok:true});}catch(e){res.status(400).json({error:e.message});}});

app.post('/api/project/:id/build-manifest', async (req,res)=>{
  try{
    const id=path.basename(req.params.id); if(id!==req.params.id) throw new Error('Invalid project id');
    const files=await readProject(id); const audit=auditFiles(files); const components=files['index.html']?extractComponents(files['index.html']):[]; const design=buildDesignSystem(req.body?.prompt||'');
    const manifest={schemaVersion:'2.0',projectId:id,generatedAt:new Date().toISOString(),entry:'index.html',files:Object.keys(files),components,designSystem:design,quality:{score:audit.score,checks:audit.checks},ai:{provider:req.body?.provider||'local-first',model:OLLAMA_MODEL},production:{responsive:true,seo:true,aeo:true,geo:true,accessibility:true}};
    await fs.writeFile(path.join(PROJECTS_DIR,id,'build-manifest.json'),JSON.stringify(manifest,null,2)); res.json({ok:true,manifest});
  }catch(e){res.status(400).json({error:e.message});}
});

app.post('/api/project/:id/library/component', async (req,res)=>{
  try{ const id=path.basename(req.params.id); const files=await readProject(id); const html=files['index.html']||''; const type=String(req.body?.type||'').trim(); if(!type) throw new Error('component type required'); const comps=extractComponents(html).filter(x=>x.type===type); if(!comps.length) throw new Error('component not found'); const c=comps[0]; const item={id:`${safeSlug(type)}-${Date.now()}`,name:req.body?.name||type,type:'component',description:req.body?.description||`Reusable ${type} component`,tags:['ai-web-studio',type,'reusable'],component:c,content:c.preview,design:req.body?.design||null}; const dir=path.join(LIBRARY_DIR,item.id); await fs.mkdir(dir,{recursive:true}); const now=new Date().toISOString(); const manifest={...item,createdAt:now,updatedAt:now}; await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)); await fs.writeFile(path.join(dir,'content.txt'),c.preview); res.json({ok:true,item:manifest}); }
  catch(e){res.status(400).json({error:e.message});}
});

app.get('/api/project/:id',async(req,res)=>{try{const files=await readProject(req.params.id);res.json({id:req.params.id,files:Object.entries(files).map(([name,content])=>({name,content}))});}catch(e){res.status(404).json({error:e.message});}});
app.post('/api/project/:id/edit',async(req,res)=>{try{const instruction=String(req.body?.instruction||'').trim();if(!instruction)return res.status(400).json({error:'instruction required'});const current=await readProject(req.params.id);if(!current['index.html'])return res.status(404).json({error:'project not found'});let files,provider='manual-fallback',aiError=null;try{files=await ollamaGenerate('',req.body?.spec||{},current,instruction);provider='ollama-file-agent';}catch(e){aiError=e.message;files=current;}await saveFiles(req.params.id,files);res.json({id:req.params.id,provider,aiError,files:Object.entries(files).map(([name,content])=>({name,content}))});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/project/:id/save',async(req,res)=>{try{const files=validateFiles(Object.fromEntries((req.body?.files||[]).map(x=>[x.name,x.content])));await saveFiles(req.params.id,files);res.json({ok:true});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/project/:id/file/:name',async(req,res)=>{try{const id=path.basename(req.params.id);if(id!==req.params.id)throw new Error('Invalid project id');const safe=path.basename(req.params.name);if(safe!==req.params.name||safe.includes('..'))throw new Error('Invalid file name');const allowed=/^(index|style|app|robots|sitemap)\.[a-z0-9]+$/i;if(!allowed.test(safe))throw new Error('File not allowed');const content=await fs.readFile(path.join(PROJECTS_DIR,id,safe),'utf8');res.type(path.extname(safe)||'text/plain').send(content);}catch{res.status(404).json({error:'file not found'});}});
app.get('/api/project/:id/diff', async (req,res)=>{try{const id=path.basename(req.params.id);if(id!==req.params.id)throw new Error('Invalid project id');const current=await readProject(id);const from=String(req.query.from||'current');const to=String(req.query.to||'current');let before=current,after=current;if(from!=='current')before=await restoreVersion(id,path.basename(from));if(to!=='current')after=await restoreVersion(id,path.basename(to));const files=[...new Set([...Object.keys(before),...Object.keys(after)])].map(name=>({name,changed:(before[name]||'')!==(after[name]||''),hunks:diffLines(before[name]||'',after[name]||'')}));res.json({from,to,files});}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/ai/code-action',async(req,res)=>{try{const action=String(req.body?.action||'').trim();const code=String(req.body?.code||'');if(!action||!code)return res.status(400).json({error:'action and code required'});const result=await aiCodeAction(action,code,req.body?.language||'html',req.body?.context||'');res.json({ok:true,result,model:OLLAMA_MODEL});}catch(e){res.status(503).json({ok:false,error:e.message});}});
app.get('/api/project/:id/versions', async (req,res)=>{try{res.json({versions:await listVersions(req.params.id)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/project/:id/versions', async (req,res)=>{try{const files=req.body?.files||{}; const v=await snapshotProject(req.params.id,files,req.body?.label||'checkpoint'); res.json(v)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/project/:id/versions/:versionId/restore', async (req,res)=>{try{const files=await restoreVersion(req.params.id,req.params.versionId); await saveFiles(req.params.id,files); res.json({files:Object.entries(files).map(([name,content])=>({name,content}))})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/terminal', async (req,res)=>{try{res.json(terminalCommand(req.body?.command,req.body?.projectId||'none'))}catch(e){res.status(400).json({ok:false,error:e.message})}});


// V1.0 Studio APIs
app.get('/api/projects', async (req,res)=>{
  try{
    const entries=await fs.readdir(PROJECTS_DIR,{withFileTypes:true});
    const projects=[];
    for(const e of entries){
      if(!e.isDirectory()) continue;
      const metaPath=path.join(PROJECTS_DIR,e.name,'project.json');
      try{ projects.push(JSON.parse(await fs.readFile(metaPath,'utf8'))); }
      catch{ projects.push({id:e.name,name:e.name,updatedAt:null}); }
    }
    projects.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));
    res.json({projects});
  }catch(e){res.status(500).json({error:e.message});}
});

app.post('/api/projects/save-meta', async (req,res)=>{
  try{
    const {id,name,description}=req.body||{};
    if(!id||path.basename(id)!==id) throw new Error('Invalid project id');
    const dir=path.join(PROJECTS_DIR,id); await fs.mkdir(dir,{recursive:true});
    const meta={id,name:name||'Untitled Project',description:description||'',updatedAt:new Date().toISOString()};
    await fs.writeFile(path.join(dir,'project.json'),JSON.stringify(meta,null,2));
    res.json(meta);
  }catch(e){res.status(400).json({error:e.message});}
});

app.get('/api/project/:id/tree', async (req,res)=>{
  try{
    const id=path.basename(req.params.id); if(id!==req.params.id) throw new Error('Invalid project id');
    const dir=path.join(PROJECTS_DIR,id); const names=await fs.readdir(dir,{withFileTypes:true});
    res.json({tree:names.filter(x=>x.isFile()&&x.name!=='project.json').map(x=>({name:x.name,type:'file'}))});
  }catch(e){res.status(404).json({error:e.message});}
});

app.get('/api/project/:id/export', async (req,res)=>{
  try{
    const archiver=(await import('archiver')).default;
    const id=path.basename(req.params.id); if(id!==req.params.id) throw new Error('Invalid project id');
    const dir=path.join(PROJECTS_DIR,id);
    res.attachment(`${id}.zip`);
    const archive=archiver('zip',{zlib:{level:9}});
    archive.on('error',err=>{ if(!res.headersSent) res.status(500); res.end(); });
    archive.pipe(res); archive.directory(dir,false,{ignore:['project.json']}); await archive.finalize();
  }catch(e){if(!res.headersSent)res.status(500).json({error:e.message});}
});

app.get('/api/studio/diagnostics', async (req,res)=>{
  const versions={node:process.version,platform:process.platform,arch:process.arch};
  const checks=[];
  for(const [label,fn] of [['Projects directory',()=>fs.access(PROJECTS_DIR)],['Ollama endpoint',()=>fetch(`${OLLAMA_URL}/api/tags`)]]){
    try{await fn();checks.push({label,ok:true});}catch(e){checks.push({label,ok:false,detail:e.message});}
  }
  res.json({versions,checks});
});

app.listen(8787,()=>console.log(`AI Web Studio API V2.0: http://localhost:8787 | Ollama: ${OLLAMA_URL} | Model: ${OLLAMA_MODEL}`));
